# Generated by Django 2.0.6 on 2019-03-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=20)),
                ('fecha_inicio_proyecto', models.DateField(verbose_name='Fecha de Inicio Proyecto')),
                ('fecha_fin_proyecto', models.DateField(verbose_name='Fecha de Fin Proyecto')),
                ('estado_proyecto', models.CharField(max_length=10)),
                ('descripcion_proyecto', models.TextField()),
            ],
        ),
    ]
