# Generated by Django 2.0.6 on 2019-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=20)),
                ('fecha_inicio_proyecto', models.DateField(verbose_name='Fecha de Inicio Proyecto')),
                ('fecha_fin_proyecto', models.DateField(verbose_name='Fecha de Fin Proyecto')),
                ('estado_proyecto', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Suspendido', 'Suspendido'), ('Finalizado', 'Finalizado')], default='Activo', max_length=25)),
                ('descripcion_proyecto', models.TextField()),
            ],
        ),
    ]
