# Generated by Django 2.0.6 on 2019-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='descripcion',
            field=models.TextField(default='none'),
        ),
    ]
