# Generated by Django 2.0.6 on 2019-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_proyecto',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Suspendido', 'Suspendido'), ('Finalizado', 'Finalizado')], default='Activo', max_length=25),
        ),
    ]
