# Generated by Django 2.0.6 on 2019-03-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20190329_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin_proyecto',
            field=models.DateTimeField(verbose_name='Fecha de Fin Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio_proyecto',
            field=models.DateTimeField(verbose_name='Fecha de Inicio Proyecto'),
        ),
    ]
