# Generated by Django 2.0.6 on 2019-04-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_teammember_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado'), ('Suspendido', 'Suspendido')], default='Pendiente', max_length=25),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin_estimada',
            field=models.DateField(verbose_name='Fecha de Fin Estimada'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_ini_estimada',
            field=models.DateField(verbose_name='Fecha de Inicio Estimada'),
        ),
    ]
