# Generated by Django 2.0.6 on 2019-05-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20190429_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='horas_dia',
            field=models.TimeField(null=True),
        ),
    ]
