# Generated by Django 2.0.6 on 2019-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_teammember_horas_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='horas_dia',
        ),
    ]
