# Generated by Django 2.0.6 on 2019-05-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_remove_teammember_horas_desarrollador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_fin_estimada',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_ini_estimada',
        ),
    ]
