# Generated by Django 2.0.6 on 2019-04-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_sprint_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='team_member',
        ),
    ]
