# Generated by Django 2.0.6 on 2019-04-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_auto_20190429_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_estimada',
            field=models.DateField(verbose_name='Fecha de Fin Estimada'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_ini_estimada',
            field=models.DateField(verbose_name='Fecha de Inicio Estimada'),
        ),
    ]
