# Generated by Django 2.0.6 on 2019-04-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_remove_sprint_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Terminado', 'Terminado')], default='Pendiente', max_length=25),
        ),
    ]
