# Generated by Django 2.0.6 on 2019-05-12 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0007_dialaboral_sprinteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sprinteammember',
            name='Sprint',
        ),
        migrations.RemoveField(
            model_name='sprinteammember',
            name='dias_laborales',
        ),
        migrations.RemoveField(
            model_name='sprinteammember',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='SprinTeamMember',
        ),
        migrations.AddField(
            model_name='dialaboral',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.SprintTeamMember'),
        ),
    ]
