# Generated by Django 2.0.6 on 2019-05-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0008_auto_20190511_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintteammember',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='sprintteammember',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='dialaboral',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.TeamMember'),
        ),
        migrations.DeleteModel(
            name='SprintTeamMember',
        ),
    ]
