# Generated by Django 2.0.6 on 2019-05-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0009_auto_20190512_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialaboral',
            name='horas_laborales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
