# Generated by Django 2.0.6 on 2019-05-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0010_auto_20190512_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialaboral',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
    ]
