# Generated by Django 2.0.6 on 2019-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0012_auto_20190512_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialaboral',
            name='dia',
            field=models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], max_length=20, null=True),
        ),
    ]
