# Generated by Django 2.0.6 on 2019-05-13 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0013_auto_20190512_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialaboral',
            name='dia',
            field=models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], null=True),
        ),
        migrations.AlterField(
            model_name='dialaboral',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
