# Generated by Django 2.0.6 on 2019-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0015_auto_20190512_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='dias_habiles',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
