# Generated by Django 2.0.6 on 2019-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0016_sprint_dias_habiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='dias_habiles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
