# Generated by Django 2.0.6 on 2019-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('contraseña_usuario', models.CharField(max_length=100)),
                ('estado_usuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('ci_usuario', models.CharField(max_length=10)),
                ('telefono_usuario', models.CharField(max_length=50)),
                ('direccion_usuario', models.CharField(max_length=200)),
                ('descripcion_usuario', models.TextField()),
            ],
        ),
    ]
