# Generated by Django 2.0.6 on 2019-03-28 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ci_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='prueba',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
