# Generated by Django 2.0.6 on 2019-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='rol.Permiso', verbose_name='Permisos de Administración'),
        ),
    ]
