# Generated by Django 2.0.6 on 2019-03-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190328_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='prueba',
            new_name='usuario',
        ),
    ]
