# Generated by Django 2.0.6 on 2019-03-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20190328_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='web',
        ),
    ]
