# Generated by Django 2.0.6 on 2019-03-29 02:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_auto_20190328_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='AgregarUsuario',
        ),
    ]
