# Generated by Django 2.0.6 on 2019-03-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20190329_0412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='GestionarUsuario',
        ),
    ]
