# Generated by Django 2.0.6 on 2019-03-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20190329_0433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestionarUsuario',
            new_name='Usuario',
        ),
    ]
