# Generated by Django 2.0.6 on 2019-03-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20190329_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_usuario',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
    ]
