# Generated by Django 2.0.6 on 2019-05-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flujo', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AddField(
            model_name='fase',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flujo.Flujo'),
        ),
    ]
