# Generated by Django 2.0.6 on 2019-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20190429_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
