# Generated by Django 2.0.6 on 2019-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('descripcion_cliente', models.TextField(max_length=300)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('ruc_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=30)),
            ],
        ),
    ]
