# Generated by Django 2.0.6 on 2019-03-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('descripcion_cliente', models.TextField()),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('ruc_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=30)),
            ],
        ),
    ]
