# Generated by Django 2.0.6 on 2019-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='descripcion_cliente',
            field=models.CharField(max_length=500),
        ),
    ]
