# Generated by Django 2.0.6 on 2019-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190328_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='descripcion_cliente',
            field=models.TextField(),
        ),
    ]
