# Generated by Django 2.0.6 on 2019-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del User Story')),
                ('duracion_estimada', models.DurationField()),
                ('valor_negocio', models.IntegerField()),
                ('prioridad', models.IntegerField()),
                ('valor_tecnico', models.IntegerField()),
                ('priorizacion', models.IntegerField()),
            ],
        ),
    ]
