# Generated by Django 2.0.6 on 2019-04-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'Asignado'), (2, 'Finalizado')], default=0),
        ),
    ]
