# Generated by Django 2.0.6 on 2019-04-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_userstory_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.PositiveIntegerField(choices=[(2, 'Pendiente'), (1, 'Asignado'), (0, 'Finalizado')], default=0),
        ),
    ]
