# Generated by Django 2.0.6 on 2019-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_auto_20190411_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoolModelBro',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='priorizacion',
        ),
        migrations.AlterField(
            model_name='userstory',
            name='valor_negocio',
            field=models.PositiveIntegerField(),
        ),
    ]
