# Generated by Django 2.0.6 on 2019-06-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_horas_team_member'),
        ('userstory', '0002_auto_20190526_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
        migrations.AddField(
            model_name='nota',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
    ]
