# Generated by Django 2.0.6 on 2019-05-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20190429_2045'),
        ('tipoUserStory', '0002_auto_20190429_2212'),
        ('userstory', '0002_userstory_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='estado_flujo',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=30),
        ),
        migrations.AddField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flujo.Flujo'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tipoUserStory.TipoUserStory'),
        ),
    ]
