# Generated by Django 2.0.6 on 2019-06-11 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0003_auto_20190610_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
    ]
