# Generated by Django 2.0.6 on 2019-06-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20190526_1628'),
        ('sprint', '0002_horas_team_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userstory', '0004_auto_20190610_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_fase', models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], max_length=30)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flujo.Fase')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.UserStory')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
