# Generated by Django 2.0.6 on 2019-05-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20190429_2045'),
        ('userstory', '0004_auto_20190501_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flujo.Fase'),
        ),
    ]
