# Generated by Django 2.0.6 on 2019-06-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0005_auto_20190612_0916'),
    ]

    operations = [
    ]
