# Generated by Django 2.0.6 on 2019-06-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20190526_1628'),
        ('userstory', '0006_auto_20190612_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.Fase'),
        ),
    ]
