# Generated by Django 2.0.6 on 2019-05-03 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0006_actividad_archivo_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
