# Generated by Django 2.0.6 on 2019-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0006_auto_20190612_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='binario',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
