# Generated by Django 2.0.6 on 2019-06-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0007_actividad_fase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='fase',
            new_name='us_fase',
        ),
    ]
