# Generated by Django 2.0.6 on 2019-06-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20190526_1628'),
        ('userstory', '0008_auto_20190612_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='us_fase',
        ),
        migrations.AddField(
            model_name='actividad',
            name='fase_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.Fase'),
        ),
    ]
