# Generated by Django 2.0.6 on 2019-05-11 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_auto_20190501_1852'),
        ('userstory', '0008_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='sprints_asignados',
            field=models.ManyToManyField(blank=True, related_name='userstory_sprint_asignado', to='sprint.Sprint'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='duracion_estimada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado_fase',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], default='To Do', max_length=30),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujo.Fase'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del User Story'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flujo.Flujo'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoUserStory.TipoUserStory'),
        ),
    ]
