# Generated by Django 2.0.6 on 2019-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0009_auto_20190504_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='duracion_estimada',
            field=models.TimeField(),
        ),
    ]
