# Generated by Django 2.0.6 on 2019-06-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0009_auto_20190612_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.Fase'),
        ),
    ]
