# Generated by Django 2.0.6 on 2019-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0010_auto_20190505_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del User Story'),
        ),
    ]
