# Generated by Django 2.0.6 on 2019-06-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0011_auto_20190612_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estado_fase',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], default='To Do', max_length=30),
        ),
    ]
