# Generated by Django 2.0.6 on 2019-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0011_auto_20190505_1501'),
        ('userstory', '0009_auto_20190503_2156'),
    ]

    operations = [
    ]
