# Generated by Django 2.0.6 on 2019-05-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_auto_20190501_1852'),
        ('userstory', '0011_auto_20190505_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='sprint_asignados',
            field=models.ManyToManyField(blank=True, related_name='userstory_sprint_asignado', to='sprint.Sprint'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujo.Fase'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flujo.Flujo'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoUserStory.TipoUserStory'),
        ),
    ]
