# Generated by Django 2.0.6 on 2019-06-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0012_actividad_estado_fase'),
        ('userstory', '0007_archivo_binario'),
    ]

    operations = [
    ]
