# Generated by Django 2.0.6 on 2019-05-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0012_merge_20190508_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujo.Fase'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flujo.Flujo'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.TeamMember'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoUserStory.TipoUserStory'),
        ),
    ]
