# Generated by Django 2.0.6 on 2019-06-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0013_merge_20190613_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='estado_fase',
            field=models.CharField(blank=True, choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], max_length=30, null=True),
        ),
    ]
