# Generated by Django 2.0.6 on 2019-05-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0013_auto_20190508_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
