# Generated by Django 2.0.6 on 2019-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_auto_20190501_1852'),
        ('userstory', '0013_auto_20190506_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='sprint_asignados',
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprints_asignados',
            field=models.ManyToManyField(blank=True, related_name='userstory_sprint_asignado', to='sprint.Sprint'),
        ),
    ]
