# Generated by Django 2.0.6 on 2019-05-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0014_auto_20190509_1003'),
        ('userstory', '0013_auto_20190508_1014'),
        ('userstory', '0012_merge_20190506_1455'),
    ]

    operations = [
    ]
