# Generated by Django 2.0.6 on 2019-06-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_horas_team_member'),
        ('userstory', '0015_auto_20190623_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstimaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_estimada', models.PositiveIntegerField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint')),
            ],
        ),
        migrations.AlterField(
            model_name='userstory',
            name='duracion_restante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialestimaciones',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.UserStory'),
        ),
    ]
